### ISSUE TITLE
Attempted to Create SAs getting error

### ISSUE THREAD

**Issue by vipertongn** [fionera/TeamDriveManager#12]
Hello, 

So I'm sure I set up the items requested in the readme.  When I set up teamdrivemanager everything seems to be fine and I'm able to list the drives and everything.  

When I try to create SAs using the combinations command. I end up with this error "level-error msg=" Please supply the ProjectID to use""  How do I supply the projectid?  I have the existing project created and I have an ID but not sure how to supply it.

**Comment by catthehacker** [comment]
It creates project for you, also [how to create service accounts with project_accounts_keys is described here](https://github.com/fionera/TeamDriveManager/wiki#creating-service-accounts-with-teamdrivemanger).
