### ISSUE TITLE
Infected Windows Release ?

### ISSUE THREAD

**Issue by alx-xlx** [fionera/TeamDriveManager#7]
![](https://i.imgur.com/baYE2px.png)

Checking this on - https://www.virustotal.com/gui/file/ea4e9b80b1fbb3be88bbe4e94f4eb57f900db71493a9247e5078f1a655af90c0/detection

**Comment by fionera** [comment]
When 1 of 69 (nice) Antivirus Tools says its bad and all the others dont say anything it is probably just a false alarm

**Comment by catthehacker** [comment]
What is even MaxSecure??? Sounds like some niche weak AV.
